In [34]:
import sddk
import requests
import json
import pandas as pd
pd.set_option('display.max_columns', 200)

import numpy as np

In [9]:
s = sddk.cloudSession("sciencedata.dk", "SDAM_root", "648597@au.dk")

Your ScienceData username (e.g. '123456@au.dk'): 648597@au.dk
Your ScienceData password: ········
connection with shared folder established with you as its owner
endpoint variable has been configured to: https://sciencedata.dk/files/SDAM_root/

# Import EDH dataset with "origo_clean" column

In [12]:
# this does not work, since the JSON is unproperly formatted - as a list with one string element - the string encapsulates all content

### EDH = s.read_file("https://sciencedata.dk/files/SDAM_root/SDAM_data/EDH/public/EDH_people_clean_origo_2021-08-11.json", "df")
### EDH = sddk.read_file("https://sciencedata.dk/public/b6b6afdb969d378b70929e86e58ad975/EDH_people_clean_origo_2021-08-11.json")

reading a publicly shared file

In [31]:
resp_json = requests.get("https://sciencedata.dk/public/b6b6afdb969d378b70929e86e58ad975/EDH_people_clean_origo_2021-08-11.json").json()
resp_json_eval = eval(resp_json[0])
EDH = pd.DataFrame(resp_json_eval)
EDH.head(5)

,responsible_individual,type_of_inscription,letter_size,not_after,literature,work_status,height,diplomatic_text,name,cognomen,...,occupation,origo,geography,origo_clean,age: days,social_economic_legal_history,military,age: months,supernomen,age: hours
0,Feraudi,epitaph,3.2-2 cm,0130,"AE 1983, 0192.; M. Annecchino, Puteoli 4/5, 19...",provisional,33 cm,D M / NONIAE P F OPTATAE / ET C IVLIO ARTEMONI...,Noniae P.f. Optatae,Optata,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Feraudi,epitaph,3.2-2 cm,0130,"AE 1983, 0192.; M. Annecchino, Puteoli 4/5, 19...",provisional,33 cm,D M / NONIAE P F OPTATAE / ET C IVLIO ARTEMONI...,C. Iulio Artemoni,Artemo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Feraudi,epitaph,3.2-2 cm,0130,"AE 1983, 0192.; M. Annecchino, Puteoli 4/5, 19...",provisional,33 cm,D M / NONIAE P F OPTATAE / ET C IVLIO ARTEMONI...,C. Iulius C.f. Optatus,Optatus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Feraudi,epitaph,4 cm,0200,"AE 1983, 0080. (A); A. Ferrua, RAL 36, 1981, 1...",no image,28 cm,C SEXTIVS PARIS / QVI VIXIT / ANNIS LXX,C. Sextius Paris,Paris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Feraudi,honorific inscription,4.5-3 cm,0170,"AE 1983, 0518. (B); J. González, ZPE 52, 1983,...",provisional,(37) cm,[ ]VMMIO [ ] / [ ]ISENNA[ ] / [ ] XV[ ] / [ ] / [,[P. M]ummio [P.f. Gal. S]isenna[e Rutiliano],Sisenna+ Rutilianus+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
EDH.head(5)

,responsible_individual,type_of_inscription,letter_size,not_after,literature,work_status,height,diplomatic_text,name,cognomen,nomen,person_id,gender,people,depth,material,type_of_monument,province_label,width,transcription,country,uri,findspot_ancient,last_update,modern_region,findspot_modern,language,id,edh_geography_uri,commentary,trismegistos_uri,not_before,external_image_uris,fotos,longitude,latitude,idno_tm,placenames_refs,text_edition,origdate_text,layout_execution,layout_execution_text,support_objecttype,support_objecttype_text,support_material,support_material_text,support_decoration,keywords_term,keywords_term_text,type_of_inscription_clean,type_of_inscription_certainty,height_cm,width_cm,depth_cm,material_clean,type_of_monument_clean,type_of_monument_certainty,province_label_clean,province_label_certainty,country_clean,country_certainty,findspot_ancient_clean,findspot_ancient_certainty,modern_region_clean,modern_region_certainty,findspot_modern_clean,findspot_modern_certainty,findspot_clean,findspot_certainty,origdate_text_clean,clean_text_conservative,clean_text_interpretive_word,clean_text_interpretive_sentence,praenomen,age: years,findspot,year_of_find,tribus,status,present_location,religion,occupation,origo,geography,origo_clean,age: days,social_economic_legal_history,military,age: months,supernomen,age: hours
0,Feraudi,epitaph,3.2-2 cm,0130,"AE 1983, 0192.; M. Annecchino, Puteoli 4/5, 19...",provisional,33 cm,D M / NONIAE P F OPTATAE / ET C IVLIO ARTEMONI...,Noniae P.f. Optatae,Optata,Nonia,1,female,{},2.7 cm,"Marmor, geädert / farbig",tabula,Latium et Campania (Regio I),34 cm,D(is) M(anibus) / Noniae P(ubli) f(iliae) Opta...,Italy,https://edh-www.adw.uni-heidelberg.de/edh/insc...,"Cumae, bei",2014-04-07,Campania,"Cuma, bei",Latin,HD000001,https://edh-www.adw.uni-heidelberg.de/edh/geog...,(C): 2. Hälfte 1. - Anfang 2. Jh. - AE; Ende ...,https://www.trismegistos.org/text/251193,0071,{},{},14.0551,40.8472,251193,"[http://www.trismegistos.org/place/033152, htt...",Dis Manibus Noniae Publi filiae Optatae et Cai...,71 AD – 130 AD,21,unbestimmt,257,Tafel,,"Marmor, geädert / farbig",1000,92,Grabinschrift,epitaph,Certain,33.0,34.0,2.7,Marble,tabula,Certain,Latium et Campania (Regio I),Certain,Italy,Certain,Cumae,Estimated,Campania,Certain,"Cuma, bei",Certain,NULL,NULL,71 AD – 130 AD,D M Noniae P f Optatae et C Iulio Artemoni par...,Dis Manibus Noniae Publi filiae Optatae et Cai...,Dis Manibus Noniae Publi filiae Optatae et Cai...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Feraudi,epitaph,3.2-2 cm,0130,"AE 1983, 0192.; M. Annecchino, Puteoli 4/5, 19...",provisional,33 cm,D M / NONIAE P F OPTATAE / ET C IVLIO ARTEMONI...,C. Iulio Artemoni,Artemo,Iulius,2,male,{},2.7 cm,"Marmor, geädert / farbig",tabula,Latium et Campania (Regio I),34 cm,D(is) M(anibus) / Noniae P(ubli) f(iliae) Opta...,Italy,https://edh-www.adw.uni-heidelberg.de/edh/insc...,"Cumae, bei",2014-04-07,Campania,"Cuma, bei",Latin,HD000001,https://edh-www.adw.uni-heidelberg.de/edh/geog...,(C): 2. Hälfte 1. - Anfang 2. Jh. - AE; Ende ...,https://www.trismegistos.org/text/251193,0071,{},{},14.0551,40.8472,251193,"[http://www.trismegistos.org/place/033152, htt...",Dis Manibus Noniae Publi filiae Optatae et Cai...,71 AD – 130 AD,21,unbestimmt,257,Tafel,,"Marmor, geädert / farbig",1000,92,Grabinschrift,epitaph,Certain,33.0,34.0,2.7,Marble,tabula,Certain,Latium et Campania (Regio I),Certain,Italy,Certain,Cumae,Estimated,Campania,Certain,"Cuma, bei",Certain,NULL,NULL,71 AD – 130 AD,D M Noniae P f Optatae et C Iulio Artemoni par...,Dis Manibus Noniae Publi filiae Optatae et Cai...,Dis Manibus Noniae Publi filiae Optatae et Cai...,C.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Feraudi,epitaph,3.2-2 cm,0130,"AE 1983, 0192.; M. Annecchino, Puteoli 4/5, 19...",provisional,33 cm,D M / NONIAE P F OPTATAE / ET C IVLIO ARTEMONI...,C. Iulius C.f. Optatus,Optatus,Iulius,3,male,{},2.7 cm,"Marmor, geädert / farbig",tabula,Latium et Campania (Regio I),34 cm,D(is) M(anibus) / Noniae P(ubli) f(iliae) Opta...,Italy,https://edh-www.adw.uni-heidelberg.de/edh/insc...,"Cumae, bei",2014-04-07,Campania,"Cuma, bei",Latin,HD000001,https://edh-www.adw.uni-heidelberg.de/edh/geog...,(C): 2. Hälfte 1. - Anfang 2. Jh. - AE; Ende ...,https://www.trismegistos.org/text/251193,0071,{},{},14.0551,40.8472,251193,"[http://www.trismegistos.org/place/033152, htt...",Dis Manibus Noniae Publi filiae Optatae et Cai...,71 AD – 130 AD,21,unbestimmt,257,Tafel,,"Marmor, geädert / farbig",1000,92,Grabinschrift,epitaph,Certain,33.0,34.0,2.7,Marble,tabula,Certain,Latium et Campania (Regio I),Certain,Italy,Certain,Cumae,Estimated,Campania,Certain,"Cuma, bei",Certain,NULL,NULL,71 AD – 130 AD,D M Noniae P f Optatae et C Iulio Artemoni par...,Dis Manibus Noniae Publi filiae Optatae et Cai...,Dis Manibus Noniae Publi filiae Optatae et Cai...,C.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Feraudi,epitaph,4 cm,0200,"AE 1983, 0080. (A); A. Ferrua, RAL 36, 1981, 1...",no image,28 cm,C SEXTIVS PARIS / QVI VIXIT / ANNIS LXX,C. Sextius Paris,Paris,Sextius,1,male,{},NaN,marble: rocks - metamorphic rocks,tabula,Roma,85 cm,C(aius) Sextius Paris / qui vixit / annis LXX,Italy,https://edh-www.adw.uni-heidelberg.de/edh/insc...,Roma,2014-04-07,Lazio,Roma,Latin,HD000002,https://edh-www.adw.uni-heidelberg.de/edh/geog...,AE 1983: Breite: 35 cm.,https://www.trismegistos.org/text/265631,0051,{},{},12.4823,41.8955,265631,"[http://www.trismegistos.org/place/000172, htt...",Caius Sextius Paris qui vixit annis LXX ...,51 AD – 200 AD,21,unbestimmt,257,Tafel,48,Marmor,1000,92,Grabinschrift,epitaph,Certain,28.0,85.0,NaN,Marble,tabula,Certain,Roma,Certain,Italy,Certain,Roma,Certain,Lazio,Certain,Roma,Certain,"Via Nomentana, S. Alessandro, Kirche",Certain,51 AD – 200 AD,C Sextius Paris qui vixit annis LXX,Caius Sextius Paris qui vixit annis LXX,Caius Sextius Paris qui vixit annis LXX,C.,70,"Via Nomentana, S. Alessandro, Kirche",1937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Feraudi,honorific inscription,4.5-3 cm,0170,"AE 1983, 0518. (B); J. González, ZPE 52, 1983,...",provisional,(37) cm,[ ]VMMIO [ ] / [ ]ISENNA[ ] / [ ] XV[ ] / [ ] / [,[P. M]ummio [P.f. Gal. S]isenna[e Rutiliano],Sisenna+ Rutilianus+,Mummius+,1,male,{},(12) cm,marble: rocks - metamorphic rocks,statue base,Baetica,(34) cm,[P(ublio) M]ummio [P(ubli) f(ilio)] / [Gal(eri...,Spain,https://edh-www.adw.uni-heidelberg.de/edh/insc...,NaN,2006-08-31,Sevilla,Tomares,Latin,HD000003,https://edh-www.adw.uni-heidelberg.de/edh/geog...,(B): [S]isenna ist falscher Kasus; folgende E...,https://www.trismegistos.org/text/220675,0131,{},{},-6.0459,37.3728,220675,"[http://www.trismegistos.org/place/025443, htt...",Publio Mummio Publi filio Galeria Sisennae Rut...,131 AD – 170 AD,21,unbestimmt,57,Statuenbasis,48,Marmor,1000,69,Ehreninschrift,honorific inscription,Certain,37.0,34.0,12.0,Marble,statue base,Certain,Baetica,Certain,Spain,Certain,NULL,NULL,Sevilla,Certain,Tomares,Certain,NULL,NULL,131 AD – 170 AD,ummio isenna Xv,Publio Mummio Publi filio Galeria Sisennae Rut...,Publio Mummio Publi filio Galeria Sisennae Rut...,P.+,NaN,NaN,before 1975,Galeria+,senatorial order,"Sevilla, Privatbesitz",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
origo_unique = EDH["origo_clean"].unique().tolist()
origo_unique[:20]

[nan,
 'Batavus',
 'Italicensis',
 'Laodicenus Asia',
 'Iponobensis',
 'Pannonius',
 'Serdica',
 'tate Veliocassium',
 'oriunda Mauretania',
 'Da[---]',
 'Germanicopolis in Bithynia',
 'Singilensis',
 'Dertona',
 'Lucerinus',
 'Caladunus',
 'Thrax',
 'Alandrinus',
 'Italo',
 'Igabrensis',
 'Turdulus Vetus']

In [38]:
len(origo_unique)

1310

# Import Hanson and Pleiades

In [39]:
roman_cities = sddk.read_file("https://sciencedata.dk/public/cd2e3b7206a89bf833cf3648703452e9/roman_cities.json", "df")
roman_cities.head(5)

reading a publicly shared file

,Primary Key,Ancient Toponym,Modern Toponym,Province,Country,Barrington Atlas Rank,Barrington Atlas Reference,Start Date,End Date,Longitude (X),Latitude (Y),Select Bibliography,Area,Estimate Basis,Civic Status,Structure,num_of_structures,ID,pop_sample,pop_est,pop_diff
0,Hanson2016_1,Abae,Kalapodi,Achaea,Greece,4 or 5,55 D3,-600,NaN,22.933333,38.583333,BNP; Hansen 2006; Hansen and Nielsen 2004; PEC...,16.0,Walls,[Rights and privileges],"[Acropolis, Agora, Temple of Apollo, Theatre, ...",5,1,NaN,1700.0,NaN
1,Hanson2016_2,Acharnae,Acharnes,Achaea,Greece,3,59 B2,-600,NaN,23.734088,38.083473,BNP; DGRG; PECS; Sear 2006.,NaN,None,None,"[Sanctuary of Apollo Argyieus, Sanctuary of He...",3,2,NaN,1000.0,NaN
2,Hanson2016_3,Acraephia,Akraifnio,Achaea,Greece,3,55 E4,-600,NaN,23.219702,38.452606,BNP; DGRG; Hansen and Nielsen 2004; PECS; Sear...,NaN,None,None,"[Acropolis, Agora, Fountain, Temple of Apollo ...",7,3,NaN,1000.0,NaN
3,Hanson2016_4,Aegina,Aigina,Achaea,Greece,2,59 A3,-600,NaN,23.428500,37.750074,BNP; DGRG; Hansen 2006; Hansen and Nielsen 200...,52.0,Inhabited area,[Rights and privileges],"[Shrine of Aeacus, Stadium, Temple of Aphrodit...",8,4,NaN,8209.0,NaN
4,Hanson2016_5,Aegira,Aigeira,Achaea,Greece,3,58 C1,-600,NaN,22.355720,38.147951,DGRG; Hansen and Nielsen 2004.,NaN,None,None,"[Acropolis, Agora, Gymnasium, Temple of Aphrod...",8,5,NaN,1000.0,NaN

In [40]:
cities_names = roman_cities["Ancient Toponym"].tolist()

In [43]:
len([place for place in origo_unique if place in cities_names])

137

In [55]:
#url = "http://atlantides.org/downloads/pleiades/json/pleiades-places-20210822.json.gz"
url = "http://atlantides.org/downloads/pleiades/dumps/pleiades-places-20210822.csv.gz"
pleiades_places = pd.read_csv(url, compression='gzip')
pleiades_places.head(5)

,authors,bbox,connectsWith,created,creators,currentVersion,description,extent,featureTypes,geoContext,hasConnectionsWith,id,locationPrecision,maxDate,minDate,modified,path,reprLat,reprLatLong,reprLong,tags,timePeriods,timePeriodsKeys,timePeriodsRange,title,uid
0,"Becker, J., T. Elliott","13.4119837, 42.082885, 13.4119837, 42.082885",413005,2016-11-04T16:36:09Z,"jbecker, thomase",1.0,The post-Roman settlement at Alba Fucens becam...,"{""type"": ""Point"", ""coordinates"": [13.4119837, ...",settlement,NaN,NaN,48210385,precise,1453.0,640.0,2016-11-08T21:58:28Z,/places/48210385,42.082885,"42.082885,13.4119837",13.411984,NaN,M,mediaeval-byzantine,"640.0,1453.0",Borgo Medievale,ece5760c4c6d42c1a331aad543c4ecc4
1,"Becker, J., T. Elliott","11.6285463, 42.4193742, 11.6285463, 42.4193742",413393,2016-11-04T16:39:09Z,"jbecker, thomase",2.0,A major urban sanctuary at Vulci with a long p...,"{""type"": ""Point"", ""coordinates"": [11.6285463, ...",temple-2,NaN,NaN,48210386,precise,300.0,-750.0,2016-12-05T11:47:10Z,/places/48210386,42.419374,"42.4193742,11.6285463",11.628546,"sanctuary, extant remains, temple",ACHR,"archaic,classical,hellenistic-republican,roman","-750.0,300.0",Tempio Grande at Vulci,4e06898f2de74dbc9f3a3bdba6d74ba2
2,"Spann, P., DARMC, R. Talbert, S. Gillies, R. W...","-3.606772, 39.460299, -3.606772, 39.460299",NaN,2010-09-24T19:02:22Z,P.O. Spann,15.0,"An ancient settlement, likely of Celtic origin...","{""type"": ""Point"", ""coordinates"": [-3.606772, 3...",settlement,Consuegra,266518,265876,precise,640.0,-330.0,2020-09-25T03:36:50Z,/places/265876,39.460299,"39.460299,-3.606772",-3.606772,"dare:ancient=1, dare:major=1, dare:feature=maj...",HRL,"hellenistic-republican,roman,late-antique","-330.0,640.0",Consabura/Consabrum,3fb26862377912da0f866fc310bcaf0c
3,"Spann, P., R. Warner, R. Talbert, S. Gillies, ...","-0.515639, 38.988847, -0.515639, 38.988847",NaN,2010-09-24T19:02:24Z,P.O. Spann,4.0,Contestania was a region located in the southw...,"{""type"": ""Point"", ""coordinates"": [-0.515639, 3...",region,"SE coastal area, E Bastetania up to R. Júcar (...",266018,265877,related,300.0,-330.0,2019-08-03T20:55:49Z,/places/265877,38.988847,"38.988847,-0.515639",-0.515639,NaN,HR,"hellenistic-republican,roman","-330.0,300.0",Contestania (region),ff0b70ad7c02ce378753e5d02f00210c
4,"Spann, P., DARMC, R. Talbert, R. Warner, J. Be...","-2.403309, 37.241792, -2.403309, 37.241792",NaN,2010-09-24T19:02:25Z,P.O. Spann,8.0,"An ancient place, cited: BAtlas 27 C4 Cueva de...","{""type"": ""Point"", ""coordinates"": [-2.403309, 3...",mine-2,"Cueva de la Paloma, 12 miles NE Gergal",NaN,265878,precise,300.0,-330.0,2021-01-15T16:23:31Z,/places/265878,37.241792,"37.241792,-2.403309",-2.403309,"dare:major=0, copper, dare:feature=mine, dare:...",HR,"hellenistic-republican,roman","-330.0,300.0",Cueva de la Paloma,5901bbdb1e0e9ae93968083c8b013026

In [56]:
len(pleiades_places)

38494

In [57]:
#url = "http://atlantides.org/downloads/pleiades/json/pleiades-places-20210822.json.gz"
url = "http://atlantides.org/downloads/pleiades/dumps/pleiades-names-20210822.csv.gz"
pleiades_names = pd.read_csv(url, compression='gzip')
pleiades_names.head(5)

,authors,bbox,created,creators,currentVersion,description,extent,id,locationPrecision,maxDate,minDate,modified,nameAttested,nameLanguage,nameTransliterated,path,pid,reprLat,reprLatLong,reprLong,tags,timePeriods,timePeriodsKeys,timePeriodsRange,title,uid
0,"Spann, P., R. Warner, R. Talbert, T. Elliott, ...","-3.606772, 39.460299, -3.606772, 39.460299",2010-09-24T19:02:22Z,P.O. Spann,NaN,NaN,"{""type"": ""Point"", ""coordinates"": [-3.606772, 3...",consabura,precise,640.0,-330.0,2011-09-05T20:57:22Z,NaN,NaN,Consabura,/places/265876/consabura,/places/265876,39.460299,"39.460299,-3.606772",-3.606772,NaN,HRL,"hellenistic-republican,roman,late-antique","-330.0,640.0",Consabura,fc0ee157ff11ce6d2e72cd7c5df06fee
1,"Spann, P., R. Warner, R. Talbert, T. Elliott, ...","-3.606772, 39.460299, -3.606772, 39.460299",2010-09-24T19:02:22Z,P.O. Spann,NaN,NaN,"{""type"": ""Point"", ""coordinates"": [-3.606772, 3...",consabrum,precise,640.0,-330.0,2011-09-05T20:57:22Z,NaN,NaN,Consabrum,/places/265876/consabrum,/places/265876,39.460299,"39.460299,-3.606772",-3.606772,NaN,HRL,"hellenistic-republican,roman,late-antique","-330.0,640.0",Consabrum,e2b8756302fb62ff0e301710c265a3e6
2,"Spann, P., R. Warner, R. Talbert, T. Elliott, ...","-3.606772, 39.460299, -3.606772, 39.460299",2010-09-24T19:02:22Z,P.O. Spann,NaN,NaN,"{""type"": ""Point"", ""coordinates"": [-3.606772, 3...",kondabora,precise,640.0,-330.0,2011-09-05T20:57:22Z,NaN,NaN,Kondabora,/places/265876/kondabora,/places/265876,39.460299,"39.460299,-3.606772",-3.606772,NaN,HRL,"hellenistic-republican,roman,late-antique","-330.0,640.0",Kondabora,f742b67b8343a6c68f222fbf607dcbf9
3,"Becker, J.","-3.606772, 39.460299, -3.606772, 39.460299",2016-02-08T23:21:01Z,jbecker,1.0,An ethnic name used by Pliny the Elder.,"{""type"": ""Point"", ""coordinates"": [-3.606772, 3...",consaburrenses,precise,300.0,-30.0,2020-09-25T03:36:50Z,Consaburrenses,la,Consaburrenses,/places/265876/consaburrenses,/places/265876,39.460299,"39.460299,-3.606772",-3.606772,NaN,R,roman,"-30.0,300.0",Consaburrenses,ddc6939eba8aaf3729e6c254dedc90e4
4,"Spann, P., R. Warner, R. Talbert, S. Gillies, ...","-2.0, 38.0, -1.0, 39.0",2010-09-24T19:02:24Z,P.O. Spann,1.0,NaN,"{""type"": ""Polygon"", ""coordinates"": [[[-2.0, 38...",contestania,rough,300.0,-330.0,2016-12-15T02:27:38Z,Contestania,la,Contestania,/places/265877/contestania,/places/265877,38.500000,"38.5,-1.5",-1.500000,NaN,HR,"hellenistic-republican,roman","-330.0,300.0",Contestania,f4d5e22c62f479e2f1241850023ab2c0

In [58]:
len(pleiades_names)

34627

In [61]:
pleiades_settlements = pleiades_places[pleiades_places["featureTypes"].str.contains("settlement")]
len(pleiades_settlements)

12958

In [69]:
pleiades_settlements_list = pleiades_settlements["title"].tolist()
pleiades_settlements_list = [place.split("/") for place in pleiades_settlements_list]

In [70]:
pleiades_settlements_list[:3]

[['Borgo Medievale'],
 ['Consabura', 'Consabrum'],
 ['Dianium', 'Hemeroskopeion']]

In [63]:
len([place for place in origo_unique if place in pleiades_settlements_list])

125

In [71]:
matches = []
for place in origo_unique:
    for settl_list in pleiades_settlements_list:
        if place in settl_list:
            matches.append(place)

In [72]:
len(matches)

213

In [ ]:
pleiades_settlements_list = [place.split("/") for place in pleiades_settlements_list]